// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Support both VITE_* and NEXT_PUBLIC_* environment variable prefixes.
const SUPABASE_URL = (
  import.meta.env.VITE_SUPABASE_URL ||
  import.meta.env.VITE_PUBLIC_SUPABASE_URL ||
  import.meta.env.NEXT_PUBLIC_SUPABASE_URL ||
  import.meta.env.NEXT_PUBLIC_VITE_SUPABASE_URL ||
  null
);
const SUPABASE_PUBLISHABLE_KEY = (
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.VITE_PUBLIC_SUPABASE_KEY ||
  import.meta.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.NEXT_PUBLIC_SUPABASE_KEY ||
  null
);

// Indicate whether configuration looks valid
export const SUPABASE_CONFIGURED = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

if (!SUPABASE_CONFIGURED) {
  // Friendly, actionable logs for missing configuration
  console.error(
    '[supabase] Missing environment variables. Expected one of VITE_SUPABASE_URL or NEXT_PUBLIC_SUPABASE_URL and a publishable key.'
  );
}

const storage = typeof window !== 'undefined' ? localStorage : undefined;

// If not configured, export a safe fallback that surfaces meaningful errors
function makeNotConfiguredClient() {
  const err = new Error('Supabase client not configured. Check SUPABASE_URL and publishable key.');
  type FallbackResult = { data: null; error: Error };
  type FallbackQuery = PromiseLike<FallbackResult> & {
    select: () => FallbackQuery;
    order: () => FallbackQuery;
    eq: () => FallbackQuery;
    in: () => FallbackQuery;
    single: () => FallbackQuery;
    maybeSingle: () => FallbackQuery;
  };

  const rejected = async (): Promise<FallbackResult> => ({ data: null, error: err });

  const builder = (): FallbackQuery => {
    const query = {
      select: () => query,
      order: () => query,
      eq: () => query,
      in: () => query,
      single: () => query,
      maybeSingle: () => query,
      then: (onfulfilled, onrejected) => rejected().then(onfulfilled, onrejected),
    } satisfies FallbackQuery;

    return query;
  };

  return {
    auth: {
      getSession: async () => ({ data: { session: null }, error: err }),
      onAuthStateChange: () => ({
        data: {
          subscription: {
            unsubscribe: () => undefined,
          },
        },
      }),
      signInWithPassword: rejected,
      signUp: rejected,
      signOut: rejected,
    },
    from: (_: string) => builder(),
    insert: rejected,
    update: rejected,
    delete: rejected,
    rpc: rejected,
  } as unknown as ReturnType<typeof createClient>;
}

// Create a real client when configuration is present
export const supabase = SUPABASE_CONFIGURED
  ? createClient<Database>(SUPABASE_URL as string, SUPABASE_PUBLISHABLE_KEY as string, {
      auth: {
        storage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : makeNotConfiguredClient();

// Import the supabase client like this:
// import { supabase, SUPABASE_CONFIGURED } from "@/integrations/supabase/client";
